# Generated by Django 3.0.14 on 2022-06-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userprofile_id', models.CharField(default='', max_length=100)),
                ('userprofile_firstname', models.CharField(default='', max_length=100)),
                ('userprofile_lastname', models.CharField(default='', max_length=100)),
                ('userprofile_username', models.CharField(default='', max_length=100)),
                ('userprofile_email', models.CharField(default='', max_length=100)),
                ('userprofile_dob', models.CharField(default='', max_length=100)),
                ('userprofile_phoneno', models.CharField(default='', max_length=100)),
                ('userprofile_password', models.CharField(default='', max_length=500)),
                ('userprofile_conpassword', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
