# Generated by Django 4.0.4 on 2022-06-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('reg_dealer_id', models.AutoField(primary_key=True, serialize=False)),
                ('dealer_first_name', models.CharField(max_length=150, null=True, unique=True)),
                ('dealer_last_name', models.CharField(max_length=150, null=True, unique=True)),
                ('dealer_mobile_number', models.CharField(max_length=150, null=True, unique=True)),
                ('dealer_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('dealer_email', models.EmailField(max_length=200)),
                ('dealer_status', models.CharField(choices=[('a', 'active'), ('i', 'in-active'), ('d', 'deleted')], default='a', max_length=1)),
                ('password', models.CharField(max_length=150, null=True, unique=True)),
                ('confirm_password', models.CharField(max_length=150, null=True, unique=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='manageusers.address')),
            ],
        ),
    ]
