# Generated by Django 4.0.4 on 2022-06-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0003_alter_dealers_dealer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAddress',
            fields=[
                ('s_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('S_city', models.CharField(max_length=150, null=True, unique=True)),
                ('S_area', models.CharField(max_length=150, null=True, unique=True)),
                ('S_country', models.CharField(max_length=150, null=True, unique=True)),
                ('S_postalcode', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('reg_salesagent_id', models.AutoField(primary_key=True, serialize=False)),
                ('salesagent_first_name', models.CharField(max_length=150, null=True, unique=True)),
                ('salesagent_last_name', models.CharField(max_length=150, null=True, unique=True)),
                ('salesagent_mobile_number', models.CharField(max_length=150, null=True, unique=True)),
                ('salesagent_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('salesagent_email', models.EmailField(max_length=200)),
                ('salesagent_status', models.CharField(choices=[('active', 'active'), ('in-active', 'in-active'), ('delete', 'deleted')], default='active', max_length=20)),
                ('s_password', models.CharField(max_length=150, null=True, unique=True)),
                ('s_confirm_password', models.CharField(max_length=150, null=True, unique=True)),
                ('s_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saddress', to='manageusers.salesaddress')),
            ],
        ),
    ]
