# Generated by Django 4.0.4 on 2022-06-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0004_salesaddress_salesagent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesagent',
            old_name='s_address_id',
            new_name='salesagent_address_id',
        ),
        migrations.RenameField(
            model_name='salesagent',
            old_name='s_confirm_password',
            new_name='salesagent_confirm_password',
        ),
        migrations.RenameField(
            model_name='salesagent',
            old_name='s_password',
            new_name='salesagent_password',
        ),
    ]
