# Generated by Django 4.0.4 on 2022-06-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0005_rename_s_address_id_salesagent_salesagent_address_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesaddress',
            old_name='s_address_id',
            new_name='salesagent_address_id',
        ),
        migrations.RenameField(
            model_name='salesaddress',
            old_name='S_area',
            new_name='salesagent_area',
        ),
        migrations.RenameField(
            model_name='salesaddress',
            old_name='S_city',
            new_name='salesagent_city',
        ),
        migrations.RenameField(
            model_name='salesaddress',
            old_name='S_postalcode',
            new_name='salesagent_country',
        ),
        migrations.RenameField(
            model_name='salesaddress',
            old_name='S_country',
            new_name='salesagent_postalcode',
        ),
    ]
