# Generated by Django 4.0.5 on 2022-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0009_remove_address_email_remove_dealers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=None, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='dealers',
            name='email',
            field=models.EmailField(default=None, max_length=200, null=True),
        ),
    ]
