# Generated by Django 4.0.5 on 2022-06-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0011_dealers_user_id_dealers_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='user_uuid',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='manageusers.address'),
        ),
    ]
