# Generated by Django 4.0.5 on 2022-06-16 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageusers', '0013_remove_dealers_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='dealer_status',
            field=models.CharField(choices=[('active', 'active'), ('in-active', 'in-active'), ('delete', 'deleted')], default='in-active', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('reg_salesagent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('phone', models.CharField(max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('salesagent_status', models.CharField(choices=[('active', 'active'), ('in-active', 'in-active'), ('delete', 'deleted')], default='in-active', max_length=20)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='manageusers.address')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
