# Generated by Django 4.0.5 on 2022-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0014_alter_dealers_dealer_status_salesagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesagent',
            name='salesagent_image',
            field=models.ImageField(blank=True, null=True, upload_to='salesagent_images'),
        ),
    ]
