# Generated by Django 4.0.5 on 2022-06-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0015_salesagent_salesagent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address1', to='manageusers.address'),
        ),
    ]
