# Generated by Django 4.0.4 on 2022-05-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_category_category_last_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=150, null=True, unique=True)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_attributes', models.TextField(verbose_name='Item Details JSON')),
                ('product_descriptions', models.TextField(max_length=300, null=True, unique=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
