# Generated by Django 4.0.4 on 2022-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_attributes',
            field=models.TextField(null=True, verbose_name='Item Details JSON'),
        ),
    ]
